
services:


  vacations-database-service:

    image: vacations-database-image

    build: /Database

    container_name: vacations-database-container

    ports:
      - 3306:3306

    environment:
      MYSQL_HOST: 167.71.240.80
      MYSQL_DATABASE: vacations
      MYSQL_USER: yoss
      MYSQL_PASSWORD: yoss1234
      MYSQL_RANDOM_ROOT_PASSWORD : 1

    restart: unless-stopped

    volumes:
      - vacations-volume:/var/lib/mysql



  vacations-backend-service:

    image: vacations-backend-image

    build: 
      context: ./Backend
      dockerfile: Dockerfile.prod

    container_name: vacations-backend-container

    ports:
      - 3001:3001

    environment:
      PORT: 3001
      MYSQL_HOST: 167.71.240.80 
      MYSQL_DATABASE: vacations
      MYSQL_USER: yoss
      MYSQL_PASSWORD: yoss1234
      MYSQL_RANDOM_ROOT_PASSWORD : 1


    restart: unless-stopped

    depends_on:
      - vacations-database-service



  vacations-frontend-service:

    image: vacations-frontend-image

    build: 
      context: ./Frontend
      dockerfile: Dockerfile.prod

    container_name: vacations-frontend-container

    ports:
      - 80:80

    restart: unless-stopped

    depends_on:
      - vacations-database-service
      - vacations-backend-service


  vacations-pma-service:

    image: phpmyadmin/phpmyadmin
    
    container_name: vacations-pma-container

    ports:
      - 8080:80

    environment:
      PMA_HOST: vacations-database-service

    links:
      - vacations-database-service

    restart: unless-stopped

    depends_on:
      - vacations-database-service



volumes:
  vacations-volume:


# docker-compose -f docker-compose.prod.yml up -d 
